services:

  api:
    build: ./backend
    container_name: novatech-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://novatech:novatech@db:5432/novatech
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: novatech-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: novatech
      POSTGRES_PASSWORD: novatech
      POSTGRES_DB: novatech
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # sem "ports" aqui -> não fica exposto pra internet

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: novatech-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data: